spring:
  application:
    name: calendar

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update

  liquibase:
    change-log: classpath:liquibase/changelog-master.yaml

server:
  servlet:
    context-path: /api

app:
  calendar:
    url: https://xmlcalendar.ru/data
#    url: https://xmlcalendar.ru/datatestfail
    countryList: ru
#    countryList: ru,by,kz,uz
    yearList: 2024
#    yearList: 2020,2021,2022,2023,2024
  loadCalendarInterval: 60000

rabbitmq:
  exchange: calendar_exchange
  routing:
    originalInfoKey: original_info_key
    originalErrorKey: original_error_key
    finalInfoKey: final_info_key
    finalErrorKey: final_error_key
  queue:
    originalInfo: original_info
    originalError: original_error
    finalInfo: final_info
    finalError: final_error
