spring:
  application:
    name: calendar

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update

server:
  servlet:
    context-path: /api

app:
  calendar:
    url: https://xmlcalendar.ru/data
    countryList: ru,by,kz,uz
    yearList: 2020,2021,2022,2023,2024
  loadCalendarInterval: 50000